export default {
  items: [
    {
      kind: 'youtube#video',
      etag: 'e1ADSPxu47wEi6-cC5IHjOV3gMg',
      id: 'CtpdMkKvB6U',
      snippet: {
        publishedAt: '2022-10-03T01:00:13Z',
        channelId: 'UCTkXRDQl0luXxVQrRQvWS6w',
        title: "hi, I'm Dream.",
        description:
					"hi, I'm Dream, and this is what I look like.\n\nAfter years of being completely faceless online, I finally decided to do a face reveal.\n\nFollow my socials:\n➽ Twitter - @dream\n➽ Instagram - @dreamwastaken\n➽ Snapchat - @dreampublic\n\nGeorgeNotFound will be uploading a video of us meeting for the first time ever soon, so make sure to be ready for that...\n\nthank you all from the bottom of my heart. I appreciate you all more than you could ever know.",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/CtpdMkKvB6U/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/CtpdMkKvB6U/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/CtpdMkKvB6U/hqdefault.jpg',
            width: 480,
            height: 360,
          },
        },
        channelTitle: 'Dream',
        tags: [
          'minecraft',
          'dream',
          'dream minecraft',
          'face reveal',
          'dream face',
          'dream irl',
          'dream face reveal',
        ],
        categoryId: '20',
        liveBroadcastContent: 'none',
        localized: {
          title: "hi, I'm Dream.",
          description:
						"hi, I'm Dream, and this is what I look like.\n\nAfter years of being completely faceless online, I finally decided to do a face reveal.\n\nFollow my socials:\n➽ Twitter - @dream\n➽ Instagram - @dreamwastaken\n➽ Snapchat - @dreampublic\n\nGeorgeNotFound will be uploading a video of us meeting for the first time ever soon, so make sure to be ready for that...\n\nthank you all from the bottom of my heart. I appreciate you all more than you could ever know.",
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT5M42S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '18390424',
        likeCount: '2234360',
        favoriteCount: '0',
        commentCount: '296542',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'E6F0Ls-0PL90mr2k60RE2ocmFF4',
      id: '5paBeSE3fRY',
      snippet: {
        publishedAt: '2022-10-02T17:32:43Z',
        channelId: 'UCqZQlzSHbVJrwrn5XvzrzcA',
        title:
					'Manchester City v. Manchester United | PREMIER LEAGUE HIGHLIGHTS | 10/2/2022 | NBC Sports',
        description:
					'Hat-trick performances from Phil Foden and Erling Haaland helped guide Manchester City to a dominant 6-3 victory over rivals Manchester United at the Etihad. #NBCSports #PremierLeague #ManCity #ManUnited \n» Subscribe to NBC Sports: https://www.youtube.com/nbcsports?sub_confirmation=1\n» Watch Live Sports on NBCSports.com: http://www.nbcsports.com/live\n» Get more Premier League news on NBC Sports: https://nbcsports.com/soccer/premier-league\n\nWant more Premier League? Check out Peacock Premium: https://peacocktv.com/premierleague\n\nNBC Sports Group serves sports fans 24/7 with premier live events, insightful studio shows, and compelling original programming. NBC Sports is an established leader in the sports media landscape with an unparalleled collection of sports properties that include the Olympics, NFL, Premier League, NASCAR, PGA TOUR, the Kentucky Derby, Tour de France, French Open, IndyCar and many more.\n\nSubscribe to our channel for the latest sporting news and highlights!\n\nThe Premier League across NBC Sports Group launched in 2013 with their biggest and broadest programming commitment to-date in the United States. With live multi-platform coverage of all 380 games, analysis from best-in-class talent and extensive surrounding coverage all week long, NBC Sports Group has become the ultimate destination for new and existing Premier League fans.\n\nThe Premier League maintains strong and consistent reach across NBC, USA Network, CNBC, and NBC Sports Group’s live streaming products, led by the biggest stars and most prestigious teams in the world.\n\nVisit NBC Sports: https://www.nbcsports.com\nFind NBC Sports on Facebook: https://www.facebook.com/NBCSports\nFollow NBC Sports on Twitter: https://twitter.com/nbcsports\nFollow NBC Sports on Instagram: https://www.instagram.com/nbcsports/\n\nhttps://www.nbcsports.com/nfl/sunday-night-football\nhttps://nbcsports.com/motors/nascar\nhttps://nbcsports.com/soccer/premier-league\n\nManchester City v. Manchester United | PREMIER LEAGUE HIGHLIGHTS | 10/2/2022 | NBC Sports\nhttps://www.youtube.com/nbcsports',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/5paBeSE3fRY/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/5paBeSE3fRY/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/5paBeSE3fRY/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/5paBeSE3fRY/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/5paBeSE3fRY/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'NBC Sports',
        tags: [
          'nbc sports',
          'premier league highlights',
          'english premier league',
          'premier league soccer',
          'premier league live',
          'english premier league today',
          'premier league 2022/23',
          'manchester city vs manchester united',
          'erling haaland',
          'erling haaland goals',
          'erling haaland manchester city',
          'man city vs man united',
          'man city',
          'phil foden goal',
          'phil foden highlights',
          'man city vs man united highlight',
          'man united',
          'manchester city highlights',
          'man united highlights',
          'man city vs man utd 6-3',
        ],
        categoryId: '17',
        liveBroadcastContent: 'none',
        localized: {
          title:
						'Manchester City v. Manchester United | PREMIER LEAGUE HIGHLIGHTS | 10/2/2022 | NBC Sports',
          description:
						'Hat-trick performances from Phil Foden and Erling Haaland helped guide Manchester City to a dominant 6-3 victory over rivals Manchester United at the Etihad. #NBCSports #PremierLeague #ManCity #ManUnited \n» Subscribe to NBC Sports: https://www.youtube.com/nbcsports?sub_confirmation=1\n» Watch Live Sports on NBCSports.com: http://www.nbcsports.com/live\n» Get more Premier League news on NBC Sports: https://nbcsports.com/soccer/premier-league\n\nWant more Premier League? Check out Peacock Premium: https://peacocktv.com/premierleague\n\nNBC Sports Group serves sports fans 24/7 with premier live events, insightful studio shows, and compelling original programming. NBC Sports is an established leader in the sports media landscape with an unparalleled collection of sports properties that include the Olympics, NFL, Premier League, NASCAR, PGA TOUR, the Kentucky Derby, Tour de France, French Open, IndyCar and many more.\n\nSubscribe to our channel for the latest sporting news and highlights!\n\nThe Premier League across NBC Sports Group launched in 2013 with their biggest and broadest programming commitment to-date in the United States. With live multi-platform coverage of all 380 games, analysis from best-in-class talent and extensive surrounding coverage all week long, NBC Sports Group has become the ultimate destination for new and existing Premier League fans.\n\nThe Premier League maintains strong and consistent reach across NBC, USA Network, CNBC, and NBC Sports Group’s live streaming products, led by the biggest stars and most prestigious teams in the world.\n\nVisit NBC Sports: https://www.nbcsports.com\nFind NBC Sports on Facebook: https://www.facebook.com/NBCSports\nFollow NBC Sports on Twitter: https://twitter.com/nbcsports\nFollow NBC Sports on Instagram: https://www.instagram.com/nbcsports/\n\nhttps://www.nbcsports.com/nfl/sunday-night-football\nhttps://nbcsports.com/motors/nascar\nhttps://nbcsports.com/soccer/premier-league\n\nManchester City v. Manchester United | PREMIER LEAGUE HIGHLIGHTS | 10/2/2022 | NBC Sports\nhttps://www.youtube.com/nbcsports',
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT16M15S',
        dimension: '2d',
        definition: 'hd',
        caption: 'true',
        licensedContent: true,
        regionRestriction: {
          allowed: ['GU', 'MP', 'PR', 'US', 'VI'],
        },
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '892990',
        likeCount: '15371',
        favoriteCount: '0',
        commentCount: '1774',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'mGyqqKC-7AF5cjUQl5UzH0gbq6Q',
      id: 'oIgCd-4oDzI',
      snippet: {
        publishedAt: '2022-10-02T06:12:19Z',
        channelId: 'UCqFzWxSCi39LnW1JKFR3efg',
        title: 'ManningCast Cold Open - SNL',
        description:
					"Peyton and Eli Manning (Miles Teller, Andrew Dismukes) take a break from their ManningCast to break down what's happening on the premiere of Saturday Night Live.\n\nSaturday Night Live. Stream now on Peacock: https://pck.tv/3uQxh4q\n\nSubscribe to SNL: https://goo.gl/tUsXwM\nStream Current Full Episodes: http://www.nbc.com/saturday-night-live\n\nWATCH PAST SNL SEASONS\nGoogle Play - http://bit.ly/SNLGooglePlay\niTunes - http://bit.ly/SNLiTunes\n\nSNL ON SOCIAL\nSNL Instagram: http://instagram.com/nbcsnl\nSNL Facebook: https://www.facebook.com/snl\nSNL Twitter: https://twitter.com/nbcsnl\nSNL TikTok: https://www.tiktok.com/@nbcsnl\n\nGET MORE NBC\nLike NBC: http://Facebook.com/NBC\nFollow NBC: http://Twitter.com/NBC\nNBC Tumblr: http://NBCtv.tumblr.com/\nYouTube: http://www.youtube.com/nbc\nNBC Instagram: http://instagram.com/nbc\n\n#SNL #MilesTeller #KendrickLamar #SNL48",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/oIgCd-4oDzI/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/oIgCd-4oDzI/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/oIgCd-4oDzI/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/oIgCd-4oDzI/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/oIgCd-4oDzI/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Saturday Night Live',
        tags: [
          'SNL10012022',
          'snl',
          'saturday night live',
          'snl 48',
          'saturday night live season 48',
          'miles teller',
          'snl host Miles teller',
          'football',
          'sports',
          'jon hamm',
          'mikey day',
          'andrew dismukes',
          'heidi gardner',
          'marcello hernández',
          'molly kearney',
          'michael Longfellow',
          'sarah sherman',
          'devon walker',
          'hurricane ian',
          'florida',
          'top gun maverick',
          'comedy',
          'sketch',
          'host',
          'Whiplash',
          'War Dogs',
          'Bleed for This',
          'Top Gun: Maverick',
          'The Offer',
          'kendrick lamar',
          'miles teller host',
          'season 48',
          'snl season 48',
          'manningcast',
        ],
        categoryId: '23',
        liveBroadcastContent: 'none',
        localized: {
          title: 'ManningCast Cold Open - SNL',
          description:
						"Peyton and Eli Manning (Miles Teller, Andrew Dismukes) take a break from their ManningCast to break down what's happening on the premiere of Saturday Night Live.\n\nSaturday Night Live. Stream now on Peacock: https://pck.tv/3uQxh4q\n\nSubscribe to SNL: https://goo.gl/tUsXwM\nStream Current Full Episodes: http://www.nbc.com/saturday-night-live\n\nWATCH PAST SNL SEASONS\nGoogle Play - http://bit.ly/SNLGooglePlay\niTunes - http://bit.ly/SNLiTunes\n\nSNL ON SOCIAL\nSNL Instagram: http://instagram.com/nbcsnl\nSNL Facebook: https://www.facebook.com/snl\nSNL Twitter: https://twitter.com/nbcsnl\nSNL TikTok: https://www.tiktok.com/@nbcsnl\n\nGET MORE NBC\nLike NBC: http://Facebook.com/NBC\nFollow NBC: http://Twitter.com/NBC\nNBC Tumblr: http://NBCtv.tumblr.com/\nYouTube: http://www.youtube.com/nbc\nNBC Instagram: http://instagram.com/nbc\n\n#SNL #MilesTeller #KendrickLamar #SNL48",
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT7M8S',
        dimension: '2d',
        definition: 'hd',
        caption: 'true',
        licensedContent: true,
        regionRestriction: {
          blocked: [],
        },
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '922740',
        likeCount: '11114',
        favoriteCount: '0',
        commentCount: '1372',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'l498_vnIPzSQ_5qpFnmGm_tffJ8',
      id: 'xyviGKwPntA',
      snippet: {
        publishedAt: '2022-10-02T17:05:45Z',
        channelId: 'UCHYoe8kQ-7Gn9ASOlmI0k6Q',
        title: 'Food Theory: Do NOT Eat NyQuil Chicken!',
        description:
					"SUBSCRIBE for Every Tasty Theory! ►► https://bit.ly/2CdCooV  \n \nI can't believe I need to say this but DON'T EAT chicken cooked in NyQuil! Like Tide Pods and questionable Pink Sauce, there are things that are just not meant to be ingested. Today I'm going to explain why the NyQuil chicken challenge is dangerous and why we need to stop trying viral food hacks that we KNOW are bad for us just for the views. Safety first and let's dive in!\n \nGet Your TheoryWear NOW! ► https://theorywear.com/\nSUBSCRIBE for Every Theory! ►► https://bit.ly/2CdCooV  \n \nWant More FOOD THEORY?\nYou've Been SCAMMED! (Supermarket Secrets) ► https://youtu.be/EqviBPG2uPE\nTootsie Pops, How Many Licks? ► https://youtu.be/qOS5NAdyWDw\nNever Order McDonald's Medium Fries! ► https://youtu.be/c_jnZkVlNtw\nKool Aid Man Is A Marvel Villain! ► https://youtu.be/CuZ14w_g3WA  \nDon't Trust Your Cake! ► https://youtu.be/dulS3GGiJ7M  \n \nJoin our other Theorist Communities!\nGame Theory! ► http://bit.ly/1qV8fd6  \nFilm Theory! ► http://bit.ly/1dI8VBH  \n \nNeed Royalty Free Music for your Content? Try Epidemic Sound.\nGet A 30 Day Free Trial! ►  http://share.epidemicsound.com/theFoodTheorists\n \nCredits:\nWriters: Matthew Patrick and Justin Kuiper\nEditors: Danial \"BanditRants\" Keristoufi and Tyler Mascola\nSound Editor: Yosi Berman\n \n#NyquilChicken #NyquilChickenChallenge #nyquil #FoodHack #ChickenRecipe #Challenge #PinkSauce #FoodTheory #MatPat #GameTheory #FilmTheory",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/xyviGKwPntA/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/xyviGKwPntA/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/xyviGKwPntA/hqdefault.jpg',
            width: 480,
            height: 360,
          },
        },
        channelTitle: 'The Food Theorists',
        tags: [
          'nyquil chicken',
          'nyquil chicken challenge',
          'pink sauce',
          'the pink sauce',
          'what is nyquil chicken',
          'what is the pink sauce',
          'nyquil chicken recipe',
          'fda nyquil chicken',
          'cooking nyquil chicken',
          'chicken nyquil challenge',
          'nyquil chicken fda warning',
          'cook chicken in nyquil',
          'food theory',
          'food theorists',
          'matpat',
          'food theory pink sauce',
          'chicken recipe',
          'challenge',
          'nyquil chicken original',
          'nyquil chicken reaction',
          'nyquil chicken original video',
          'nyquil chicken meme',
        ],
        categoryId: '26',
        liveBroadcastContent: 'none',
        localized: {
          title: 'Food Theory: Do NOT Eat NyQuil Chicken!',
          description:
						"SUBSCRIBE for Every Tasty Theory! ►► https://bit.ly/2CdCooV  \n \nI can't believe I need to say this but DON'T EAT chicken cooked in NyQuil! Like Tide Pods and questionable Pink Sauce, there are things that are just not meant to be ingested. Today I'm going to explain why the NyQuil chicken challenge is dangerous and why we need to stop trying viral food hacks that we KNOW are bad for us just for the views. Safety first and let's dive in!\n \nGet Your TheoryWear NOW! ► https://theorywear.com/\nSUBSCRIBE for Every Theory! ►► https://bit.ly/2CdCooV  \n \nWant More FOOD THEORY?\nYou've Been SCAMMED! (Supermarket Secrets) ► https://youtu.be/EqviBPG2uPE\nTootsie Pops, How Many Licks? ► https://youtu.be/qOS5NAdyWDw\nNever Order McDonald's Medium Fries! ► https://youtu.be/c_jnZkVlNtw\nKool Aid Man Is A Marvel Villain! ► https://youtu.be/CuZ14w_g3WA  \nDon't Trust Your Cake! ► https://youtu.be/dulS3GGiJ7M  \n \nJoin our other Theorist Communities!\nGame Theory! ► http://bit.ly/1qV8fd6  \nFilm Theory! ► http://bit.ly/1dI8VBH  \n \nNeed Royalty Free Music for your Content? Try Epidemic Sound.\nGet A 30 Day Free Trial! ►  http://share.epidemicsound.com/theFoodTheorists\n \nCredits:\nWriters: Matthew Patrick and Justin Kuiper\nEditors: Danial \"BanditRants\" Keristoufi and Tyler Mascola\nSound Editor: Yosi Berman\n \n#NyquilChicken #NyquilChickenChallenge #nyquil #FoodHack #ChickenRecipe #Challenge #PinkSauce #FoodTheory #MatPat #GameTheory #FilmTheory",
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT12M13S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '1328163',
        likeCount: '95512',
        favoriteCount: '0',
        commentCount: '7408',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'QN2xxb02eqhqN-LM3vJ3Q_nGOV4',
      id: '3xlsR77vRQA',
      snippet: {
        publishedAt: '2022-10-02T13:16:00Z',
        channelId: 'UCVT1tPkR-fUVlO652EcO3ow',
        title: 'Hurricane Ian: One for the history books',
        description:
					'Four days after Hurricane Ian made landfall in Florida, and then again in South Carolina on Friday, there are dozens dead, millions without power, and billions in damage. Correspondent Kris van Cleave reports on the aftermath of the catastrophic storm.\n#hurricaneian #florida #hurricane \n\n"CBS Sunday Morning" features stories on the arts, music, nature, entertainment, sports, history, science and Americana, and highlights unique human accomplishments and achievements. Check local listings for CBS Sunday Morning broadcast times.\n\nSubscribe to the "CBS Sunday Morning" YouTube channel: http://bit.ly/20gXwJT\nGet more of "CBS Sunday Morning": http://cbsn.ws/1PlMmAz\nFollow "CBS Sunday Morning" on Instagram: http://bit.ly/23XunIh\nLike "CBS Sunday Morning" on Facebook: https://bit.ly/3sRgLPG\nFollow "CBS Sunday Morning" on Twitter: http://bit.ly/1RquoQb\nSubscribe to our newsletter: http://cbsn.ws/1RqHw7T\nDownload the CBS News app: http://cbsn.ws/1Xb1WC8\nTry Paramount+ free: https://bit.ly/2OiW1kZ\n\nFor video licensing inquiries, contact: licensing@veritone.com',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/3xlsR77vRQA/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/3xlsR77vRQA/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/3xlsR77vRQA/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/3xlsR77vRQA/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/3xlsR77vRQA/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'CBS Sunday Morning',
        tags: [
          'CBS Sunday Morning',
          'CBS News',
          'news',
          'hurricane ian',
          'florida',
          'south carolina',
          'dead',
          'power outage',
          'damage',
          'destruction',
          'kris van cleave',
          'aftermath',
          'catastrophe',
          'storm',
        ],
        categoryId: '25',
        liveBroadcastContent: 'none',
        localized: {
          title: 'Hurricane Ian: One for the history books',
          description:
						'Four days after Hurricane Ian made landfall in Florida, and then again in South Carolina on Friday, there are dozens dead, millions without power, and billions in damage. Correspondent Kris van Cleave reports on the aftermath of the catastrophic storm.\n#hurricaneian #florida #hurricane \n\n"CBS Sunday Morning" features stories on the arts, music, nature, entertainment, sports, history, science and Americana, and highlights unique human accomplishments and achievements. Check local listings for CBS Sunday Morning broadcast times.\n\nSubscribe to the "CBS Sunday Morning" YouTube channel: http://bit.ly/20gXwJT\nGet more of "CBS Sunday Morning": http://cbsn.ws/1PlMmAz\nFollow "CBS Sunday Morning" on Instagram: http://bit.ly/23XunIh\nLike "CBS Sunday Morning" on Facebook: https://bit.ly/3sRgLPG\nFollow "CBS Sunday Morning" on Twitter: http://bit.ly/1RquoQb\nSubscribe to our newsletter: http://cbsn.ws/1RqHw7T\nDownload the CBS News app: http://cbsn.ws/1Xb1WC8\nTry Paramount+ free: https://bit.ly/2OiW1kZ\n\nFor video licensing inquiries, contact: licensing@veritone.com',
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT4M42S',
        dimension: '2d',
        definition: 'hd',
        caption: 'true',
        licensedContent: true,
        regionRestriction: {
          blocked: ['AU', 'CA', 'JP'],
        },
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '413050',
        likeCount: '3793',
        favoriteCount: '0',
        commentCount: '999',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'qzs5ntqTjbtyl0RYHWey5t_i_WA',
      id: 'DWuvxwMt0v8',
      snippet: {
        publishedAt: '2022-10-02T16:12:06Z',
        channelId: 'UCUU3GdGuQshZFRGnxAPBf_w',
        title: 'I recreated the WORLD in LEGO...',
        description:
					'I take iconic places from around the world and rebuild them in Lego...\n\nInstagram: https://www.instagram.com/td_the_creator/\n\nTikTok: tiktok.com/@td_the_creator\n\nEmail: td.brickz@gmail.com\n\nMy Instagram photography account: https://www.instagram.com/the_boy_tygo/\n\nMusic credits:\nEpidemic Sound: https://share.epidemicsound.com/c3oiyn\nmattikott_: https://www.instagram.com/mattikott_/?hl=en\nEmix Music: https://www.youtube.com/channel/UCOokqXsS72ACKATav7wPabg\n\nGear I use:\nCamera: Canon EOS R\nMic: RODE VideoMic\nTripod: Magnus VT-4000 Fluid-Head \nLighting: Softbox lighting kit, gooseneck desk lamps, and mini led panel for camera\nEditing Software: Final Cut Pro X\nMusic: Epidemic sound, YouTube to MP3 downloader\n\nI get my Lego parts from Bricklink, the Lego store pick a brick wall, Bricks & Minifigs, scrapping sets, friends who don’t play with Lego anymore.',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/DWuvxwMt0v8/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/DWuvxwMt0v8/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/DWuvxwMt0v8/hqdefault.jpg',
            width: 480,
            height: 360,
          },
        },
        channelTitle: 'TD BRICKS',
        tags: [
          'lego',
          'lego moc',
          'lego mocs',
          'lego creation',
          'lego building',
          'lego builder',
          'lego tutorial',
          'lego world',
          'lego earth',
          'lego china',
          'i made the world in lego',
          'i made countries in lego',
          'different countries in lego',
          'lego minifigure',
          'lego minifig',
          'lego city',
          'lego ideas',
          'lego meme',
          'lego memes',
          'lego time lapse',
          'lego speed build',
        ],
        categoryId: '24',
        liveBroadcastContent: 'none',
        defaultLanguage: 'en',
        localized: {
          title: 'I recreated the WORLD in LEGO...',
          description:
						'I take iconic places from around the world and rebuild them in Lego...\n\nInstagram: https://www.instagram.com/td_the_creator/\n\nTikTok: tiktok.com/@td_the_creator\n\nEmail: td.brickz@gmail.com\n\nMy Instagram photography account: https://www.instagram.com/the_boy_tygo/\n\nMusic credits:\nEpidemic Sound: https://share.epidemicsound.com/c3oiyn\nmattikott_: https://www.instagram.com/mattikott_/?hl=en\nEmix Music: https://www.youtube.com/channel/UCOokqXsS72ACKATav7wPabg\n\nGear I use:\nCamera: Canon EOS R\nMic: RODE VideoMic\nTripod: Magnus VT-4000 Fluid-Head \nLighting: Softbox lighting kit, gooseneck desk lamps, and mini led panel for camera\nEditing Software: Final Cut Pro X\nMusic: Epidemic sound, YouTube to MP3 downloader\n\nI get my Lego parts from Bricklink, the Lego store pick a brick wall, Bricks & Minifigs, scrapping sets, friends who don’t play with Lego anymore.',
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT9M49S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '683769',
        likeCount: '23684',
        favoriteCount: '0',
        commentCount: '7144',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'LCJDa96VqBjJe3l3AheElEQw4g0',
      id: '35_ajbPPcm0',
      snippet: {
        publishedAt: '2022-10-02T16:00:26Z',
        channelId: 'UCB_qr75-ydFVKSF9Dmo6izg',
        title: 'Race Highlights | 2022 Singapore Grand Prix',
        description:
					'Our return to the Marina Bay Street Circuit was an action-packed one! Watch all the best bits from a dramatic race, as F1 returned to the streets of Singapore for the first time since 2019.\n\nFor more F1® videos, visit https://www.Formula1.com\n\nFollow F1®:\nhttps://www.instagram.com/F1\nhttps://www.facebook.com/Formula1/\nhttps://www.twitter.com/F1\nhttps://www.twitch.tv/formula1\nhttps://www.tiktok.com/@f1\n\n#F1 #SingaporeGP',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/35_ajbPPcm0/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/35_ajbPPcm0/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/35_ajbPPcm0/hqdefault.jpg',
            width: 480,
            height: 360,
          },
        },
        channelTitle: 'FORMULA 1',
        tags: [
          'F1',
          'Formula One',
          'Formula 1',
          'Sports',
          'Sport',
          'Action',
          'GP',
          'Grand Prix',
          'Auto Racing',
          'Motor Racing',
        ],
        categoryId: '17',
        liveBroadcastContent: 'none',
        localized: {
          title: 'Race Highlights | 2022 Singapore Grand Prix',
          description:
						'Our return to the Marina Bay Street Circuit was an action-packed one! Watch all the best bits from a dramatic race, as F1 returned to the streets of Singapore for the first time since 2019.\n\nFor more F1® videos, visit https://www.Formula1.com\n\nFollow F1®:\nhttps://www.instagram.com/F1\nhttps://www.facebook.com/Formula1/\nhttps://www.twitter.com/F1\nhttps://www.twitch.tv/formula1\nhttps://www.tiktok.com/@f1\n\n#F1 #SingaporeGP',
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT7M10S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        regionRestriction: {
          blocked: ['BY', 'RU'],
        },
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '4933261',
        likeCount: '116624',
        favoriteCount: '0',
        commentCount: '4714',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'VgvGkJDNIZ6tA_01RkGNx_rT3mc',
      id: 'sL-PL1hpnM0',
      snippet: {
        publishedAt: '2022-10-01T17:57:00Z',
        channelId: 'UCTSRIY3GLFYIpkR2QwyeklA',
        title: 'Low Budget Amazon Movies',
        description:
					'Sponsored by HelloFresh. For 65% off with HelloFresh plus FREE shipping, use code IMALITTLESTINKER65 at https://bit.ly/3TUa3qK\n\n00:00 - intro\n00:26 - summertime christmas\n09:59 - ally & obie\n27:57 - food box!\n\nmerch:\r\nhttps://www.drewgoodenshop.com/\r\n\r\nfollow me:\r\ntwitter - https://www.twitter.com/drewisgooden\r\ninstagram - https://www.instagram.com/drewisgooden',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/sL-PL1hpnM0/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/sL-PL1hpnM0/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/sL-PL1hpnM0/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/sL-PL1hpnM0/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/sL-PL1hpnM0/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Drew Gooden',
        tags: [
          'drew gooden',
          'comedy',
          'commentary',
          'reaction',
          'vine',
          'drew gooden vine',
          'road work ahead guy',
          'parody',
          'rant',
          'cringe',
          'summertime christmas',
          'ally & obie',
          'movie review',
          'amazon movies',
          'low budget movies',
          'prime video',
          'review',
        ],
        categoryId: '23',
        liveBroadcastContent: 'none',
        localized: {
          title: 'Low Budget Amazon Movies',
          description:
						'Sponsored by HelloFresh. For 65% off with HelloFresh plus FREE shipping, use code IMALITTLESTINKER65 at https://bit.ly/3TUa3qK\n\n00:00 - intro\n00:26 - summertime christmas\n09:59 - ally & obie\n27:57 - food box!\n\nmerch:\r\nhttps://www.drewgoodenshop.com/\r\n\r\nfollow me:\r\ntwitter - https://www.twitter.com/drewisgooden\r\ninstagram - https://www.instagram.com/drewisgooden',
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT30M4S',
        dimension: '2d',
        definition: 'hd',
        caption: 'true',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '1501596',
        likeCount: '105388',
        favoriteCount: '0',
        commentCount: '5026',
      },
    },
    {
      kind: 'youtube#video',
      etag: '2xTfLRO00zvhnX2L11CO0vzzZm0',
      id: 'dTqVocrDoy0',
      snippet: {
        publishedAt: '2022-10-02T17:00:32Z',
        channelId: 'UCvK4bOhULCpmLabd2pDMtnA',
        title: '50 Hours in the Most Isolated House on Earth',
        description:
					"Get 60 days of free Headspace here: https://headspace-web.app.link/e/YesTheory using code YESTHEORY3. Valid until October 17th\n\nBig thank you to Jake Guzman for being the reason we went and found this cabin, he's an amazing photographer check out his work here:\nhttps://www.instagram.com/jguzmannn\n\nThank you to Alex Haraus for coming with us and keeping us safe:\nhttps://www.tiktok.com/@alex.haraus\n\nWe climbed to one of the most isolated house's in the world... Please do not try this yourself. Several sections were really dangerous and had help from both Jake and Alex who were incredible. Hope you enjoy this story because we had an absolutely incredible time on this one even though it was physically challenging. Cheers!\n\n🙏🏼 Thank you for making these videos possible through your support of Seek Discomfort \n⚡️ SEEK DISCOMFORT: http://seek-discomfort.com/yes-theory\n\n✈ Book an Adventure: https://travel.yestheory.com/\n\nJOIN OUR COMMUNITY\n⁺ Seek Discomfort: https://www.youtube.com/seekdiscomfort\n📝 Follow Matt’s Newsletter: http://yestheory.com/newsletter/\n📸 Instagram -  https://www.instagram.com/yestheory/\n🐦 Twitter - https://twitter.com/yestheory\n🎬  Facebook- https://www.facebook.com/yestheory/\n\n☮️ If you want to join the Yes Fam Facebook group which is 100,000+ of our most engaged and badass community members, you can apply here: \nhttps://www.facebook.com/groups/yesfam/\n\n🎥 HOW WE MAKE OUR VIDEOS\n\n🎵 Where we find our music:\n1- Epidemic Sound. Amazing royalty free music for YouTube. Free 30 day trial here: http://share.epidemicsound.com/wFFbr  \n\n2- Musicbed. Amazing label-quality cinematic music. 30-day free trial here:\nhttp://share.mscbd.fm/YesTheory\u200b\n\n3- Artlist. 2 Months Free High Quality Music: https://artlist.io/artlist-70446/?artlist_aid=YesTheory_593&utm_source=affiliate_p&utm_medium=YesTheory_593&utm_campaign=YesTheory_593\n\n4- Soundstripe: Get 15% off by using the code YESTHEORY at the link https://soundstripe.com?fpr=yestheory\n\n🎞 Our b-roll and stock footage:\n\n2 Months Free Stock Footage Videos: https://artgrid.io/artgrid-114820/?artlist_aid=YesTheory_593&utm_source=affiliate_p&utm_medium=YesTheory_593&utm_campaign=YesTheory_593\n\nFor an amazing b-roll and footage library, checkout: http://storyblocks.com/YesTheory\u200b\n\n📈  Our Most Popular YouTube Videos\n🎬  Traveling to the least visited country in the world: https://youtu.be/ODuEl4oNae0\n🎬  Becoming Superhuman with Iceman Wim Hof: https://youtu.be/8cvhwquPqJ0\n🎬  We Helicopter Bungee Jumped with Will Smith: https://youtu.be/KSu6gRp7UBA\n\n🎙 The Yes Theory Podcast: https://spoti.fi/3sFdq6v\n\nGET IN TOUCH\n🌍 Our website -  http://www.yestheory.com \n🌍 Advertise With Us - partnerships@yestheory.com\n \nWho are we? \nWe believe that life’s greatest moments and deepest connections exist outside of your comfort zone.\n\nAsk us a Question:\nTweet us @yestheory",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/dTqVocrDoy0/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/dTqVocrDoy0/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/dTqVocrDoy0/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/dTqVocrDoy0/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/dTqVocrDoy0/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Yes Theory',
        tags: [
          'yestheory',
          'seek discomfort',
          'yes theory strangers',
          'yes theory travel',
          'yes theory subscribers',
          'getting out of your comfort zone',
          'Amazon FBA',
          'cabin',
          'isolated cabin',
          'isolated house',
          "world's most isolated house",
          'loneliest house in the world',
          'climbing mountains',
        ],
        categoryId: '24',
        liveBroadcastContent: 'none',
        localized: {
          title: '50 Hours in the Most Isolated House on Earth',
          description:
						"Get 60 days of free Headspace here: https://headspace-web.app.link/e/YesTheory using code YESTHEORY3. Valid until October 17th\n\nBig thank you to Jake Guzman for being the reason we went and found this cabin, he's an amazing photographer check out his work here:\nhttps://www.instagram.com/jguzmannn\n\nThank you to Alex Haraus for coming with us and keeping us safe:\nhttps://www.tiktok.com/@alex.haraus\n\nWe climbed to one of the most isolated house's in the world... Please do not try this yourself. Several sections were really dangerous and had help from both Jake and Alex who were incredible. Hope you enjoy this story because we had an absolutely incredible time on this one even though it was physically challenging. Cheers!\n\n🙏🏼 Thank you for making these videos possible through your support of Seek Discomfort \n⚡️ SEEK DISCOMFORT: http://seek-discomfort.com/yes-theory\n\n✈ Book an Adventure: https://travel.yestheory.com/\n\nJOIN OUR COMMUNITY\n⁺ Seek Discomfort: https://www.youtube.com/seekdiscomfort\n📝 Follow Matt’s Newsletter: http://yestheory.com/newsletter/\n📸 Instagram -  https://www.instagram.com/yestheory/\n🐦 Twitter - https://twitter.com/yestheory\n🎬  Facebook- https://www.facebook.com/yestheory/\n\n☮️ If you want to join the Yes Fam Facebook group which is 100,000+ of our most engaged and badass community members, you can apply here: \nhttps://www.facebook.com/groups/yesfam/\n\n🎥 HOW WE MAKE OUR VIDEOS\n\n🎵 Where we find our music:\n1- Epidemic Sound. Amazing royalty free music for YouTube. Free 30 day trial here: http://share.epidemicsound.com/wFFbr  \n\n2- Musicbed. Amazing label-quality cinematic music. 30-day free trial here:\nhttp://share.mscbd.fm/YesTheory\u200b\n\n3- Artlist. 2 Months Free High Quality Music: https://artlist.io/artlist-70446/?artlist_aid=YesTheory_593&utm_source=affiliate_p&utm_medium=YesTheory_593&utm_campaign=YesTheory_593\n\n4- Soundstripe: Get 15% off by using the code YESTHEORY at the link https://soundstripe.com?fpr=yestheory\n\n🎞 Our b-roll and stock footage:\n\n2 Months Free Stock Footage Videos: https://artgrid.io/artgrid-114820/?artlist_aid=YesTheory_593&utm_source=affiliate_p&utm_medium=YesTheory_593&utm_campaign=YesTheory_593\n\nFor an amazing b-roll and footage library, checkout: http://storyblocks.com/YesTheory\u200b\n\n📈  Our Most Popular YouTube Videos\n🎬  Traveling to the least visited country in the world: https://youtu.be/ODuEl4oNae0\n🎬  Becoming Superhuman with Iceman Wim Hof: https://youtu.be/8cvhwquPqJ0\n🎬  We Helicopter Bungee Jumped with Will Smith: https://youtu.be/KSu6gRp7UBA\n\n🎙 The Yes Theory Podcast: https://spoti.fi/3sFdq6v\n\nGET IN TOUCH\n🌍 Our website -  http://www.yestheory.com \n🌍 Advertise With Us - partnerships@yestheory.com\n \nWho are we? \nWe believe that life’s greatest moments and deepest connections exist outside of your comfort zone.\n\nAsk us a Question:\nTweet us @yestheory",
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT22M48S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '666188',
        likeCount: '43250',
        favoriteCount: '0',
        commentCount: '1853',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'S3jTXo8VqjbxIAT-FiNBlG0Cq2Q',
      id: 'W4SNGzEdRXU',
      snippet: {
        publishedAt: '2022-10-02T14:00:23Z',
        channelId: 'UC0QHWhjbe5fGJEPz3sVb6nw',
        title: 'TikToks To Never Show Your Doctor',
        description:
					"Keep exploring at https://brilliant.org/DoctorMike. Get started for free, and hurry—the first 200 people get 20% off an annual premium subscription.\n\nTikTok not only has bad advice about medical cures and treatments, but advertisements for some useless and misleading devices. Today I look at some dangerous and murky claims made about health and medicine on TikTok, including chiropractors, kneecaps, brain exercises, gym form on weight machines, fingernails, stem cells, neck stretchers, the spins from drinking, male birth control, sperm cells, prescription drugs for mental health, plastic surgery, bears, chest compressions, ear lobes, Rob McElhenney's body transformation, kegels, prosthetic legs, running on all fours, spicy food, raw vegan diet, eye tattoos, ab exercises, FDA approvals, foot fungus, freckle tattoos, and OnlyJayus spoon claims.\nI LOVE reading your comments and take your suggestions seriously. If there’s a subject you want me to discuss or something you’d like for me to react to, leave a comment down below. Many of my videos have been born out of suggestions directly from you, so don’t hold back!\n-Doctor Mike Varshavski\n\nHelp us continue the fight against medical misinformation and change the world through charity by becoming a Doctor Mike Resident on Patreon where every month I donate 100% of the proceeds to the charity, organization, or cause of your choice! Residents get access to bonus content, an exclusive discord community, and many other perks for just $10 a month. Become a Resident today:\n\nhttps://www.patreon.com/doctormike\n\nPlease SUBSCRIBE for new videos every Wednesday afternoon and Sunday morning!  https://goo.gl/87kYq6\n\nLet’s connect:\n\nIG https://goo.gl/41ZS7w - Doctor Mike\nReddit https://www.reddit.com/r/DoctorMike/\nTwitter https://goo.gl/kzmGs5 - Real Doctor Mike\nFacebook https://goo.gl/QH4nJS - Real Doctor Mike\n\nContact Email: DoctorMikeMedia@Gmail.com\n\nP.O. Box (send me stuffs):\n340 W 42nd St # 2695\nNY, NY 10108\n\nExecutive Producer: Doctor Mike\nProduction Director and Editor: Dan Owens\nManaging Editor and Producer: Sam Bowers\nEditor and Designer: Caroline Weigum\n\n* Select photos/videos provided by Getty Images *\n\n** The information in this video is not intended nor implied to be a substitute for professional medical advice, diagnosis or treatment. All content, including text, graphics, images, and information, contained in this video is for general information purposes only and does not replace a consultation with your own doctor/health professional **",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/W4SNGzEdRXU/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/W4SNGzEdRXU/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/W4SNGzEdRXU/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/W4SNGzEdRXU/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/W4SNGzEdRXU/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Doctor Mike',
        tags: [
          'doctor mike',
          'dr mike',
          'drmike',
          'dr. mike',
          'mikhail varshavski',
          'doctor mikhail varshavski',
          'mike varshavski',
          'doctor reacts',
          'chiropractors',
          'kneecaps',
          'brain exercises',
          'fingernails',
          'stem cells',
          'neck stretchers',
          'male birth control',
          'sperm cells',
          'plastic surgery',
          'bears',
          'chest compressions',
          'ear lobes',
          'Rob McElhenney',
          'kegels',
          'prosthetic legs',
          'running on all fours',
          'spicy food',
          'raw vegan diet',
          'eye tattoos',
          'ab exercises',
          'FDA approvals',
          'foot fungus',
          'freckle tattoos',
          'only jayus',
          'onlyjayus',
        ],
        categoryId: '27',
        liveBroadcastContent: 'none',
        defaultLanguage: 'en',
        localized: {
          title: 'TikToks To Never Show Your Doctor',
          description:
						"Keep exploring at https://brilliant.org/DoctorMike. Get started for free, and hurry—the first 200 people get 20% off an annual premium subscription.\n\nTikTok not only has bad advice about medical cures and treatments, but advertisements for some useless and misleading devices. Today I look at some dangerous and murky claims made about health and medicine on TikTok, including chiropractors, kneecaps, brain exercises, gym form on weight machines, fingernails, stem cells, neck stretchers, the spins from drinking, male birth control, sperm cells, prescription drugs for mental health, plastic surgery, bears, chest compressions, ear lobes, Rob McElhenney's body transformation, kegels, prosthetic legs, running on all fours, spicy food, raw vegan diet, eye tattoos, ab exercises, FDA approvals, foot fungus, freckle tattoos, and OnlyJayus spoon claims.\nI LOVE reading your comments and take your suggestions seriously. If there’s a subject you want me to discuss or something you’d like for me to react to, leave a comment down below. Many of my videos have been born out of suggestions directly from you, so don’t hold back!\n-Doctor Mike Varshavski\n\nHelp us continue the fight against medical misinformation and change the world through charity by becoming a Doctor Mike Resident on Patreon where every month I donate 100% of the proceeds to the charity, organization, or cause of your choice! Residents get access to bonus content, an exclusive discord community, and many other perks for just $10 a month. Become a Resident today:\n\nhttps://www.patreon.com/doctormike\n\nPlease SUBSCRIBE for new videos every Wednesday afternoon and Sunday morning!  https://goo.gl/87kYq6\n\nLet’s connect:\n\nIG https://goo.gl/41ZS7w - Doctor Mike\nReddit https://www.reddit.com/r/DoctorMike/\nTwitter https://goo.gl/kzmGs5 - Real Doctor Mike\nFacebook https://goo.gl/QH4nJS - Real Doctor Mike\n\nContact Email: DoctorMikeMedia@Gmail.com\n\nP.O. Box (send me stuffs):\n340 W 42nd St # 2695\nNY, NY 10108\n\nExecutive Producer: Doctor Mike\nProduction Director and Editor: Dan Owens\nManaging Editor and Producer: Sam Bowers\nEditor and Designer: Caroline Weigum\n\n* Select photos/videos provided by Getty Images *\n\n** The information in this video is not intended nor implied to be a substitute for professional medical advice, diagnosis or treatment. All content, including text, graphics, images, and information, contained in this video is for general information purposes only and does not replace a consultation with your own doctor/health professional **",
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT14M29S',
        dimension: '2d',
        definition: 'hd',
        caption: 'true',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '1323455',
        likeCount: '60904',
        favoriteCount: '0',
        commentCount: '2417',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'sYvg23IhTgW9sdnraPYOBqpU5ks',
      id: 'XOkpayUUvrU',
      snippet: {
        publishedAt: '2022-10-02T16:00:14Z',
        channelId: 'UCv3Kk__aFcKKx_o2686uQcw',
        title: '"Yellow Zone" | Original Animation',
        description:
					"Kinda hard to call this original since it's heavily inspired from The Stanley Parable (and maybe Portal and Vector). But it deviated so much from the cannon lol so why not.\n\nI hope you enjoy ^^\n\nMUSIC: Miyavi & PVRIS - Snakes | Arcane League of Legends | Riot Games Music\nhttps://www.youtube.com/watch?v=4UprHuO_zCc\n\nI got merch :3c\nhttps://www.sad-ist.store/\n\nSupport me on Patreon?? o-o\nhttps://www.patreon.com/SADistfied\n\nAnd I also have a Discord Server :D\nhttps://discord.gg/BQyXEDdhR4",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/XOkpayUUvrU/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/XOkpayUUvrU/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/XOkpayUUvrU/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/XOkpayUUvrU/sddefault.jpg',
            width: 640,
            height: 480,
          },
        },
        channelTitle: 'SAD-ist',
        categoryId: '1',
        liveBroadcastContent: 'none',
        localized: {
          title: '"Yellow Zone" | Original Animation',
          description:
						"Kinda hard to call this original since it's heavily inspired from The Stanley Parable (and maybe Portal and Vector). But it deviated so much from the cannon lol so why not.\n\nI hope you enjoy ^^\n\nMUSIC: Miyavi & PVRIS - Snakes | Arcane League of Legends | Riot Games Music\nhttps://www.youtube.com/watch?v=4UprHuO_zCc\n\nI got merch :3c\nhttps://www.sad-ist.store/\n\nSupport me on Patreon?? o-o\nhttps://www.patreon.com/SADistfied\n\nAnd I also have a Discord Server :D\nhttps://discord.gg/BQyXEDdhR4",
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT2M46S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '377144',
        likeCount: '100619',
        favoriteCount: '0',
        commentCount: '3615',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'oDvpzGQLeZgmX4RqXNYG94DRroA',
      id: 'eLDCS3ScSr4',
      snippet: {
        publishedAt: '2022-10-02T16:08:14Z',
        channelId: 'UCj74rJ9Lgl3WTngq675wxKg',
        title: 'ratios are a nightmare',
        description:
					"Get 20% off + FREE International Shipping with promo code\n“noodle” at MANSCAPED.com! https://mnscpd.com/noodle\n\nI'm on Patreon and Twitter also;\nhttps://www.patreon.com/LegitNoodle\nhttps://twitter.com/LegitimatNoodle\n\n00:00 - Intro\n0:29 - Part 1; Artistic Expression (and cool stuff)\n5:22 - Ad Break\n6:32 - Part 2; Gamign\n16:25 - End\n\nMusic in this video: \nFamily Guy Sting\nPikuniku - The Artist's House\nAbsolute Territory - Ken Ashcorp (this song goes into explicit detail about how the singer wants to get down with their anime panda girl OC, so. Google at your own risk.)\nOther Than That (Sting Version)\nPromised by Me - Ove Meyers\nIt Ain't Too Much (Sting Version)\nFamily Guy Sting\nLose Yourself - Eminem\nGregorian Chant - Kevin MacLeod\nmuscles (Unused) - Hiveswap\nAbel Sisters (Wii Soundfont) - Animal Crossing\nPiano concerto No 21 - Mozart\nMinuet in E Major - Boccherini\nFamily Guy Theme\nAmerican Dad Theme\n\nPatrons who supported me in making this video:\nThomas Terry II\nValenrist\nAleksi Blomqvist\nMinnesota Riley\nAlex Pierce\nOddleswoddles\nCameron Hastings\nDanno!! The Artist\nKitt\nDankPods\nAdam S\nNora Taylor\nChris Kapa\nErin\ncamwing\nMrs. Mighterbump\nChristopher Dehner II\nBlu galaxy\nKolzaru\nKevin Bacon Hervieux\nSunnychance\nthe_hesitation\nC. Coupland\nTheHiddenSpace\njulia\nSinthrex\nSindalf\nMr.Mitch2000\nCardiotherapy\nTronguy93\nAlex Howe\nPhnod\nNiels Poldervaart\nTrevor McVickar\nentropyandme\nTuBa\nROAD HORROR\n1MoreSonicRobot\nJ Miller\npocket punk\nLouis Gomez\nEluTheDerp\nJarrod Brown\nMichael Thomas\nTedtheDead\nThomas Seaver\nCitrus\nBryce Hagar\nTheTieGuy123\nMedicalFlapJacks\nHappilicious\nEnrique Palomino\nZachary Blader\nRyan Wilcoxson\nBen Maclachlan\nCameron Aller\nRydundant\nAlexander Yaws\nJuicedhornet272\nVukky\nJeheiel Smith\nCrisis Variety Hour\nVictoriaIsBored\nMailman\nVincent DeLuca\nSammy Jankis\nNici\nAdmiral Luke\nGlaurung\nLeitency\nAidan Gilbert\nJacqueline Ng\n1994FordTransit\nmicah\nChad\nBlake Wallace\nLeafCaliber\nKelly Fay\nDan (Pot Noodle)\nThe Dagda\nFinn Van Wersch\nLightningXCE\nDenis L\nEfi\nThe0regonian\nJack Claiborne\nCozzi\njacdhalina\nMila Marino\nDrew Messinger-Michaels & L. Villegas\nNiki1707\nErin King\nMisael Renteria\nThatRacc\nMarkel Nixon\nNemeia, Corporate Enchantress\nHeather Waldron\nAceDefective04\nDadwelltk\neyinjay\nRobux Generator\nPatrick\nBalty B\nDolly Fish Steak\nTravis\nJunospower\nKoshikage Yira\nKyle_Da_Red_Rebel\nWillis Harvey\nGalXSee\nPatrick Kennedy\nGeroyuni\nAsthmaticEevee\nAlabaster\nSteven Bennis\nJason Offenbaker\nKal Nelson\nBen Junya\nJ Name Dude\nI'm a Jenius!\nLegumemutton\nJadeskye\nEric Lin\nRicardo Farias\nBenjamin Thornberry\nEkin Sigic\nxplor\nAndrew Lehmann\nN30NPUM4\nKeeli D\nEdgy Hecker\npuka_tchou\nJustin Bull\nHeli\nBilly Vinson\nThe Shady Boi\nWeston Hawk\nDurkeyturkey\nStevesfinesthour\nAlex Velez\nGeff\nDamonack\nn.e.c.\namoethyst\nJacob Jernigan\nPreston Schwartz\nZach Aide\nIoannis A.\nCameron Wise\nvoodooflux\nEl Lorax\nAlex Griffin\nNDKfilms\nAlex Fernandez\nGarett\nSam Staab\nCorgiTheLad\nJanuary November\nSuperCyborg\nShrimp The Kid\nVinomakon\nRemnant John\nMalcolm Yeen\nAmora Neke Lukisan\nThings Shall Get Loud Now\nPioin\nAndroos Exists\nThe Debsters\nParallel\nEamon\nYora\nrasbros\nFirePit\nOceanMan20\nBuck\nMinh\nJB Bongrand\nandrew j.\nStuffFromDan\nMegan Ebbers\nSpriteclad\neimazuba\nConnor Johnson\nJP Benini\nCovelion\nErameys\nJoBot.11\nDevz\nJonathan Do\nEli Hinger\nTristan\nCarter J\nClefspere\nFounet\nVolraan Zebric\nJoySparx\nJoshua\nSkrimish10\nTeagan Mulford\nKatze\nSwooceMaster\nMarianna\nGrav G\nCallsign Carrot\nJesse\nTerrence P.\nRainie Parker\nRiver\nAuralytical\nWunderball\nBob Jazzypoo\nSkyeel\nZurro\nMarron Turner\nCherrySojeu\nMellow Michael\nHona\nKyle Jackson\nLama\natmur\nGranolant\nSid\nErmel Twano\nMason Wilde\nrorylori\nDylan Northrup\nWilscwil\nBrian Novius\nAvery Swanson\nSeñor Chow\nMASTER G\nSam Pratt\nManda F\nWhiteghost117\nChase Castle\nErik Larsen\nsteakhouse\nNatasha\nThe Stephen Hawkins Treadmill Experience\nCasey\nEmber Reviews\nTrey Dickerson\nJonny Champion\nAndres Rodriguez\nPo\nGrimbeanie\nFerdinand Remenec\nANTHONY DUARTE\niwavva\nReanimator\nJames  Queen\nMichael I\nAck mack\nAnxious\nCombatWombat\nAndrew Nieto\nLauren Klingele\nLiam\nGary Spinrad\nGiovanni Lupo\nSentientTurtle\nJamichael Folson\nJ1411\nMarkettt\nJayDee_3779\nEthan\nNindota\nShaggy_One\nErika\nSam Cotter\nLuke Spicer\nJesús Flores\nMashProTato\nSaltTea\nKyneos\nFruitSnackBandit\nRobert\nChristina Someone\nShin Guardian\nDoggybag\nTITO woods\nBolexle\nAP\nCojo490\nChotskies\nJimMcBubbles\nAndrew K\nMatt, flamin hot braindead.\nAndrew Ross\nCale E\nQuiet269\nNehkles\nJye Francis\nA Tree\nComrade of Homotopia\nKenneth Sabian\nnflatei0n\nLuke Shepherd\nDaniel Dorfman\nACarr\nDanny DeVoid of Life\nDanny Wolf\nDeneb\nKusinwolf\nCharles Kuzmech\nRamsey\nTheresa Kulpa\nKloud\nJesse Bartels\nJean Machine\nBenedikt Müller\nKeybladestrike1\nAllOrNothing21\nReferenceMaker\nCort\nSorry Officer\nElysium Ervin\nEuroPascal\n\n#ad",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/eLDCS3ScSr4/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/eLDCS3ScSr4/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/eLDCS3ScSr4/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/eLDCS3ScSr4/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/eLDCS3ScSr4/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Noodle',
        categoryId: '1',
        liveBroadcastContent: 'none',
        defaultLanguage: 'en',
        localized: {
          title: 'ratios are a nightmare',
          description:
						"Get 20% off + FREE International Shipping with promo code\n“noodle” at MANSCAPED.com! https://mnscpd.com/noodle\n\nI'm on Patreon and Twitter also;\nhttps://www.patreon.com/LegitNoodle\nhttps://twitter.com/LegitimatNoodle\n\n00:00 - Intro\n0:29 - Part 1; Artistic Expression (and cool stuff)\n5:22 - Ad Break\n6:32 - Part 2; Gamign\n16:25 - End\n\nMusic in this video: \nFamily Guy Sting\nPikuniku - The Artist's House\nAbsolute Territory - Ken Ashcorp (this song goes into explicit detail about how the singer wants to get down with their anime panda girl OC, so. Google at your own risk.)\nOther Than That (Sting Version)\nPromised by Me - Ove Meyers\nIt Ain't Too Much (Sting Version)\nFamily Guy Sting\nLose Yourself - Eminem\nGregorian Chant - Kevin MacLeod\nmuscles (Unused) - Hiveswap\nAbel Sisters (Wii Soundfont) - Animal Crossing\nPiano concerto No 21 - Mozart\nMinuet in E Major - Boccherini\nFamily Guy Theme\nAmerican Dad Theme\n\nPatrons who supported me in making this video:\nThomas Terry II\nValenrist\nAleksi Blomqvist\nMinnesota Riley\nAlex Pierce\nOddleswoddles\nCameron Hastings\nDanno!! The Artist\nKitt\nDankPods\nAdam S\nNora Taylor\nChris Kapa\nErin\ncamwing\nMrs. Mighterbump\nChristopher Dehner II\nBlu galaxy\nKolzaru\nKevin Bacon Hervieux\nSunnychance\nthe_hesitation\nC. Coupland\nTheHiddenSpace\njulia\nSinthrex\nSindalf\nMr.Mitch2000\nCardiotherapy\nTronguy93\nAlex Howe\nPhnod\nNiels Poldervaart\nTrevor McVickar\nentropyandme\nTuBa\nROAD HORROR\n1MoreSonicRobot\nJ Miller\npocket punk\nLouis Gomez\nEluTheDerp\nJarrod Brown\nMichael Thomas\nTedtheDead\nThomas Seaver\nCitrus\nBryce Hagar\nTheTieGuy123\nMedicalFlapJacks\nHappilicious\nEnrique Palomino\nZachary Blader\nRyan Wilcoxson\nBen Maclachlan\nCameron Aller\nRydundant\nAlexander Yaws\nJuicedhornet272\nVukky\nJeheiel Smith\nCrisis Variety Hour\nVictoriaIsBored\nMailman\nVincent DeLuca\nSammy Jankis\nNici\nAdmiral Luke\nGlaurung\nLeitency\nAidan Gilbert\nJacqueline Ng\n1994FordTransit\nmicah\nChad\nBlake Wallace\nLeafCaliber\nKelly Fay\nDan (Pot Noodle)\nThe Dagda\nFinn Van Wersch\nLightningXCE\nDenis L\nEfi\nThe0regonian\nJack Claiborne\nCozzi\njacdhalina\nMila Marino\nDrew Messinger-Michaels & L. Villegas\nNiki1707\nErin King\nMisael Renteria\nThatRacc\nMarkel Nixon\nNemeia, Corporate Enchantress\nHeather Waldron\nAceDefective04\nDadwelltk\neyinjay\nRobux Generator\nPatrick\nBalty B\nDolly Fish Steak\nTravis\nJunospower\nKoshikage Yira\nKyle_Da_Red_Rebel\nWillis Harvey\nGalXSee\nPatrick Kennedy\nGeroyuni\nAsthmaticEevee\nAlabaster\nSteven Bennis\nJason Offenbaker\nKal Nelson\nBen Junya\nJ Name Dude\nI'm a Jenius!\nLegumemutton\nJadeskye\nEric Lin\nRicardo Farias\nBenjamin Thornberry\nEkin Sigic\nxplor\nAndrew Lehmann\nN30NPUM4\nKeeli D\nEdgy Hecker\npuka_tchou\nJustin Bull\nHeli\nBilly Vinson\nThe Shady Boi\nWeston Hawk\nDurkeyturkey\nStevesfinesthour\nAlex Velez\nGeff\nDamonack\nn.e.c.\namoethyst\nJacob Jernigan\nPreston Schwartz\nZach Aide\nIoannis A.\nCameron Wise\nvoodooflux\nEl Lorax\nAlex Griffin\nNDKfilms\nAlex Fernandez\nGarett\nSam Staab\nCorgiTheLad\nJanuary November\nSuperCyborg\nShrimp The Kid\nVinomakon\nRemnant John\nMalcolm Yeen\nAmora Neke Lukisan\nThings Shall Get Loud Now\nPioin\nAndroos Exists\nThe Debsters\nParallel\nEamon\nYora\nrasbros\nFirePit\nOceanMan20\nBuck\nMinh\nJB Bongrand\nandrew j.\nStuffFromDan\nMegan Ebbers\nSpriteclad\neimazuba\nConnor Johnson\nJP Benini\nCovelion\nErameys\nJoBot.11\nDevz\nJonathan Do\nEli Hinger\nTristan\nCarter J\nClefspere\nFounet\nVolraan Zebric\nJoySparx\nJoshua\nSkrimish10\nTeagan Mulford\nKatze\nSwooceMaster\nMarianna\nGrav G\nCallsign Carrot\nJesse\nTerrence P.\nRainie Parker\nRiver\nAuralytical\nWunderball\nBob Jazzypoo\nSkyeel\nZurro\nMarron Turner\nCherrySojeu\nMellow Michael\nHona\nKyle Jackson\nLama\natmur\nGranolant\nSid\nErmel Twano\nMason Wilde\nrorylori\nDylan Northrup\nWilscwil\nBrian Novius\nAvery Swanson\nSeñor Chow\nMASTER G\nSam Pratt\nManda F\nWhiteghost117\nChase Castle\nErik Larsen\nsteakhouse\nNatasha\nThe Stephen Hawkins Treadmill Experience\nCasey\nEmber Reviews\nTrey Dickerson\nJonny Champion\nAndres Rodriguez\nPo\nGrimbeanie\nFerdinand Remenec\nANTHONY DUARTE\niwavva\nReanimator\nJames  Queen\nMichael I\nAck mack\nAnxious\nCombatWombat\nAndrew Nieto\nLauren Klingele\nLiam\nGary Spinrad\nGiovanni Lupo\nSentientTurtle\nJamichael Folson\nJ1411\nMarkettt\nJayDee_3779\nEthan\nNindota\nShaggy_One\nErika\nSam Cotter\nLuke Spicer\nJesús Flores\nMashProTato\nSaltTea\nKyneos\nFruitSnackBandit\nRobert\nChristina Someone\nShin Guardian\nDoggybag\nTITO woods\nBolexle\nAP\nCojo490\nChotskies\nJimMcBubbles\nAndrew K\nMatt, flamin hot braindead.\nAndrew Ross\nCale E\nQuiet269\nNehkles\nJye Francis\nA Tree\nComrade of Homotopia\nKenneth Sabian\nnflatei0n\nLuke Shepherd\nDaniel Dorfman\nACarr\nDanny DeVoid of Life\nDanny Wolf\nDeneb\nKusinwolf\nCharles Kuzmech\nRamsey\nTheresa Kulpa\nKloud\nJesse Bartels\nJean Machine\nBenedikt Müller\nKeybladestrike1\nAllOrNothing21\nReferenceMaker\nCort\nSorry Officer\nElysium Ervin\nEuroPascal\n\n#ad",
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT17M28S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '355630',
        likeCount: '42877',
        favoriteCount: '0',
        commentCount: '2573',
      },
    },
    {
      kind: 'youtube#video',
      etag: 'UlhGprvTF8qy4Cf-UaWHADEKULM',
      id: 'SZcupt0Yqaw',
      snippet: {
        publishedAt: '2022-10-02T07:20:53Z',
        channelId: 'UCoYfzC2zMlc9M-Odgaf6OSg',
        title: 'Kendrick Lamar - Rich Spirit + N95 (Live on SNL)',
        description:
					'Kendrick Lamar - Rich Spirit + N95 (Live on SNL) \n\nKendrick Lamar “Mr. Morale & The Big Steppers” is available now:\nhttps://KendrickLamar.lnk.to/MrMorale\nhttps://oklama.com\nhttps://www.instagram.com/kendricklamar\nhttps://twitter.com/kendricklamar\nhttps://www.facebook.com/kendricklamar\n\n#KendrickLamar #RichSpirit #N95\n\nhttp://vevo.ly/OQLLOR',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/SZcupt0Yqaw/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/SZcupt0Yqaw/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/SZcupt0Yqaw/hqdefault.jpg',
            width: 480,
            height: 360,
          },
        },
        channelTitle: 'KendrickLamarVEVO',
        tags: [
          'Kendrick lamar',
          'rich spirit',
          'N95',
          'snl',
          'Saturday night live',
        ],
        categoryId: '10',
        liveBroadcastContent: 'none',
        localized: {
          title: 'Kendrick Lamar - Rich Spirit + N95 (Live on SNL)',
          description:
						'Kendrick Lamar - Rich Spirit + N95 (Live on SNL) \n\nKendrick Lamar “Mr. Morale & The Big Steppers” is available now:\nhttps://KendrickLamar.lnk.to/MrMorale\nhttps://oklama.com\nhttps://www.instagram.com/kendricklamar\nhttps://twitter.com/kendricklamar\nhttps://www.facebook.com/kendricklamar\n\n#KendrickLamar #RichSpirit #N95\n\nhttp://vevo.ly/OQLLOR',
        },
      },
      contentDetails: {
        duration: 'PT4M40S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '614732',
        likeCount: '60790',
        favoriteCount: '0',
        commentCount: '2860',
      },
    },
    {
      kind: 'youtube#video',
      etag: '0K_KNzkHcCCCTQEWV_bcLFdsWoY',
      id: 'RLxnEWip3po',
      snippet: {
        publishedAt: '2022-10-02T18:56:32Z',
        channelId: 'UCNAf1k0yIjyGu3k9BwAg3lg',
        title: '"United have DISRESPECTED Ronaldo!" 😳 | Keane & Micah CLASH',
        description:
					"SUBSCRIBE ► https://bit.ly/SubscribeSkySportsPL\nPREMIER LEAGUE HIGHLIGHTS ► http://bit.ly/SkySportsPLHighlights2223\nRoy Keane believes Manchester United are 'disrespecting' Cristiano Ronaldo by not playing him more regularly and not allowing him to leave the club.\n\nWatch Premier League LIVE on Sky Sports here ► http://bit.ly/WatchSkyPL\n►TWITTER: https://twitter.com/skysportsPL\n►FACEBOOK: http://www.facebook.com/skysportsfootball\n►WEBSITE: http://www.skysports.com/football\n\nMORE FROM SKY SPORTS ON YOUTUBE:\n►SKY SPORTS PREMIER LEAGUE: https://bit.ly/SubscribeSkySportsPL\n►SKY SPORTS FOOTBALL: https://bit.ly/SubscribeSkyFootball\n►SKY SPORTS BOXING: http://bit.ly/SSBoxingSub\n►SKY SPORTS CRICKET: http://bit.ly/SubscribeSkyCricket\n►SOCCER AM: http://bit.ly/SoccerAMSub\n►SKY SPORTS F1: http://bit.ly/SubscribeSkyF1\n►SKY SPORTS: http://bit.ly/SkySportsSub\n►SKY SPORTS GOLF: https://bit.ly/SubscribeSkySportsGolf",
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/RLxnEWip3po/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/RLxnEWip3po/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/RLxnEWip3po/hqdefault.jpg',
            width: 480,
            height: 360,
          },
          standard: {
            url: 'https://i.ytimg.com/vi/RLxnEWip3po/sddefault.jpg',
            width: 640,
            height: 480,
          },
          maxres: {
            url: 'https://i.ytimg.com/vi/RLxnEWip3po/maxresdefault.jpg',
            width: 1280,
            height: 720,
          },
        },
        channelTitle: 'Sky Sports Premier League',
        tags: [
          'sky sports',
          'premier league',
          'Football League',
          'football',
          'Sky Sports live',
          'Sky',
          'Sports',
          'stream',
          'sky sports football',
          'premier league highlights',
          'epl other 1920',
          'Erling Haaland',
          'Football',
          'Haaland',
          'Man City',
          'Man City vs Man United',
          'Manchester City',
          'Manchester derby',
          'Premier League',
          'Sky Sports',
          'Soccer',
          'Roy Keane',
          'Keane man united',
          'Keane manchester united',
          'Man City 6-3 Man Utd',
          '6-3 man city',
          'Ronaldo',
          'Cristiano Ronaldo',
          'Heated',
          'debate',
          'keane micah',
          'micah richards',
          'Keane ronaldo',
        ],
        categoryId: '24',
        liveBroadcastContent: 'none',
        localized: {
          title: '"United have DISRESPECTED Ronaldo!" 😳 | Keane & Micah CLASH',
          description:
						"SUBSCRIBE ► https://bit.ly/SubscribeSkySportsPL\nPREMIER LEAGUE HIGHLIGHTS ► http://bit.ly/SkySportsPLHighlights2223\nRoy Keane believes Manchester United are 'disrespecting' Cristiano Ronaldo by not playing him more regularly and not allowing him to leave the club.\n\nWatch Premier League LIVE on Sky Sports here ► http://bit.ly/WatchSkyPL\n►TWITTER: https://twitter.com/skysportsPL\n►FACEBOOK: http://www.facebook.com/skysportsfootball\n►WEBSITE: http://www.skysports.com/football\n\nMORE FROM SKY SPORTS ON YOUTUBE:\n►SKY SPORTS PREMIER LEAGUE: https://bit.ly/SubscribeSkySportsPL\n►SKY SPORTS FOOTBALL: https://bit.ly/SubscribeSkyFootball\n►SKY SPORTS BOXING: http://bit.ly/SSBoxingSub\n►SKY SPORTS CRICKET: http://bit.ly/SubscribeSkyCricket\n►SOCCER AM: http://bit.ly/SoccerAMSub\n►SKY SPORTS F1: http://bit.ly/SubscribeSkyF1\n►SKY SPORTS: http://bit.ly/SkySportsSub\n►SKY SPORTS GOLF: https://bit.ly/SubscribeSkySportsGolf",
        },
      },
      contentDetails: {
        duration: 'PT6M46S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '1640846',
        likeCount: '32167',
        favoriteCount: '0',
        commentCount: '5731',
      },
    },
    {
      kind: 'youtube#video',
      etag: '_QwFzTm9AZNhKV0tPqtO9QEiVLk',
      id: 'yB1lWmEE0w0',
      snippet: {
        publishedAt: '2022-10-01T16:00:38Z',
        channelId: 'UCZpRTwgtk1H0cUAWrHZ1gzg',
        title: 'OVERNIGHT SURVIVAL CHALLENGE *IKEA ITEMS ONLY*',
        description:
					'Overnight survival challenge with Ikea items only!\nCHECK OUT OUR MERCH! ► https://jstushop.com\n\nBOOK US ON CAMEO!\nhttps://www.cameo.com/morejstu?qid=1616629868 \n\nFollow us on INSTAGRAM!\n⚡️Justin - https://www.instagram.com/itsjustinstuart\n⚡️Andrew - https://www.instagram.com/andrewscites \n\n----------------------------------------\u00ad\u00ad\u00ad\u00ad\u00ad\u00ad\u00ad\u00ad---------------------------------\u00ad-\u00ad-\u00ad-\u00ad-\u00ad-\nOur motto on this channel is LAUGH DAILY! Why is this our motto? Because we believe in the importance of laughing daily, we strive to bring joy to people\'s lives by watching our content. \n"A joyful heart is good medicine, but a crushed spirit dries up the bones."  Proverbs 17:22  We love this verse and it is the driving force behind our videos and why we do what we do! \n\n----------------------------------------\u00ad\u00ad\u00ad\u00ad\u00ad\u00ad\u00ad\u00ad---------------------------------\u00ad-\u00ad-\u00ad-\u00ad-\u00ad-\n• Contact (Business Only) : jstu@delkatalents.com',
        thumbnails: {
          default: {
            url: 'https://i.ytimg.com/vi/yB1lWmEE0w0/default.jpg',
            width: 120,
            height: 90,
          },
          medium: {
            url: 'https://i.ytimg.com/vi/yB1lWmEE0w0/mqdefault.jpg',
            width: 320,
            height: 180,
          },
          high: {
            url: 'https://i.ytimg.com/vi/yB1lWmEE0w0/hqdefault.jpg',
            width: 480,
            height: 360,
          },
        },
        channelTitle: 'JStu',
        tags: [
          'survival challenge',
          'budget challenge',
          'jstu',
          'jstu micro',
          'jstu build',
          'jstustudios',
          'ikea items only',
          'building',
          'overnight challenge',
        ],
        categoryId: '24',
        liveBroadcastContent: 'none',
        localized: {
          title: 'OVERNIGHT SURVIVAL CHALLENGE *IKEA ITEMS ONLY*',
          description:
						'Overnight survival challenge with Ikea items only!\nCHECK OUT OUR MERCH! ► https://jstushop.com\n\nBOOK US ON CAMEO!\nhttps://www.cameo.com/morejstu?qid=1616629868 \n\nFollow us on INSTAGRAM!\n⚡️Justin - https://www.instagram.com/itsjustinstuart\n⚡️Andrew - https://www.instagram.com/andrewscites \n\n----------------------------------------\u00ad\u00ad\u00ad\u00ad\u00ad\u00ad\u00ad\u00ad---------------------------------\u00ad-\u00ad-\u00ad-\u00ad-\u00ad-\nOur motto on this channel is LAUGH DAILY! Why is this our motto? Because we believe in the importance of laughing daily, we strive to bring joy to people\'s lives by watching our content. \n"A joyful heart is good medicine, but a crushed spirit dries up the bones."  Proverbs 17:22  We love this verse and it is the driving force behind our videos and why we do what we do! \n\n----------------------------------------\u00ad\u00ad\u00ad\u00ad\u00ad\u00ad\u00ad\u00ad---------------------------------\u00ad-\u00ad-\u00ad-\u00ad-\u00ad-\n• Contact (Business Only) : jstu@delkatalents.com',
        },
        defaultAudioLanguage: 'en',
      },
      contentDetails: {
        duration: 'PT23M45S',
        dimension: '2d',
        definition: 'hd',
        caption: 'false',
        licensedContent: true,
        contentRating: {},
        projection: 'rectangular',
      },
      statistics: {
        viewCount: '1053699',
        likeCount: '29131',
        favoriteCount: '0',
        commentCount: '2534',
      },
    },
  ],
};
